# Generated by Django 5.0.1 on 2024-02-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='hackeathon',
            field=models.TextField(blank=True),
        ),
    ]
