# Generated by Django 5.0.1 on 2024-02-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_userpost_hackeathon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='member',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='types',
            field=models.CharField(blank=True, choices=[('M', 'Member'), ('T', 'Team')], max_length=1, null=True),
        ),
    ]
