# Generated by Django 5.0.1 on 2024-01-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_userprofile_facebooklink_userprofile_githublink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stackoverflowlink',
            field=models.TextField(blank=True),
        ),
    ]
