# Generated by Django 5.0.1 on 2024-02-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_userpost_member_userpost_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='types',
            field=models.CharField(blank=True, choices=[('Member', 'Member'), ('Team', 'Team')], max_length=10, null=True),
        ),
    ]
