# Generated by Django 5.0.1 on 2024-02-07 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_userpost_deleted_alter_userpost_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackeathon',
            name='image',
        ),
    ]
