# Generated by Django 5.0.1 on 2024-02-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_hackeathon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='member',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Professional', 'Professional')], max_length=12, null=True),
        ),
    ]
