# Generated by Django 5.0.1 on 2024-02-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_userprofile_batch_alter_userprofile_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otherlink',
            field=models.TextField(blank=True),
        ),
    ]
