# Generated by Django 5.0.1 on 2024-02-11 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_userpost_member_alter_userprofile_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='ProfileModel',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='usercomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='intrested',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='user',
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='commentmodel_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='commentmodel_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HackeathonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rules', models.TextField()),
                ('eligibility', models.TextField()),
                ('contact', models.TextField()),
                ('link', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='hackeathonmodel_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='hackeathonmodel_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackeathon', models.TextField(blank=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('member', models.IntegerField(default=1)),
                ('types', models.CharField(blank=True, choices=[('Member', 'Member'), ('Team', 'Team')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('comments', models.ManyToManyField(blank=True, related_name='postmodel_comments', to='API.commentmodel')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='postmodel_dislikes', to=settings.AUTH_USER_MODEL)),
                ('intrested', models.ManyToManyField(blank=True, related_name='postmodel_intrested', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='postmodel_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.postmodel'),
        ),
        migrations.DeleteModel(
            name='Hackeathon',
        ),
        migrations.DeleteModel(
            name='UserComment',
        ),
        migrations.DeleteModel(
            name='UserPost',
        ),
    ]
