# Generated by Django 5.0.1 on 2024-02-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_forgotpasswordmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpasswordmodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
