# Generated by Django 5.0.1 on 2024-02-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_messagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageModel',
        ),
    ]
